# Setup
title:               Jasaindigo.com
tagline:             'Blog'
description:         'Blog'
url:                 
baseurl:             '/'
paginate:            10
permalink:           pretty

# About/contact
author: 
  name: Abasty             
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #
